apiVersion: apps/v1
kind: Deployment
metadata:
  name: last-oasis-deployment
  labels:
    app: last-oasis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: last-oasis
  template:
    metadata:
      labels:
        app: last-oasis
    spec:
      containers:
      - name: last-oasis
        image: gcr.io/maximum-security-horny-jail/steam-cmd:20210729-9
        ports:
        - containerPort: 27015
        - containerPort: 31337
        volumeMounts:
         - mountPath: /data
           name: server-disk
         - mountPath: /script
           name: custom-server
        env:
        - name: CUSTOM
          value: "/script/custom_server.sh"
        - name: PUID
          value: "50500"
        - name: PGID
          value: "50500"
        - name: UPDATE_OS
          value: "1"
        - name: UPDATE_STEAM
          value: "1"
        - name: UPDATE_SERVER
          value: "1"
        - name: PLATFORM
          value: "windows"
        - name: STEAM_APP_ID
          value: "920720"
        - name: TZ
          value: "America/Los_Angeles"
        - name: SERVER_PORT
          value: "31337"
        - name: SERVER_IP
          value: "35.209.20.79"
        - name: CUSTOMER_KEY
          valueFrom:
            secretKeyRef:
             name: steam-pw
             key: providerkey
        - name: HOSTING_KEY
          valueFrom:
            secretKeyRef:
              name: steam-pw
              key: serverkey
        - name: STEAM_UNAME
          value: "furysama_dedicated"
        - name: STEAM_PW
          valueFrom:
            secretKeyRef:
              name: steam-pw
              key: password
        - name: SERVER_IDENTIFIER
          value: "Dunkelheim"
      volumes:
      - name: custom-server
        configMap: 
          name: custom-server
          defaultMode: 0755
      - name: server-disk
        gcePersistentDisk:
         pdName: last-oasis-7018090
         fsType: ext4
