apiVersion: v1
kind: Service
metadata:
  name: last-oasis
spec:
  type: NodePort
  selector:
    app: last-oasis
  ports:
  - protocol: UDP
    port: 31337
    targetPort: 31337
    nodePort: 31337
    name: "last-oasis"
  - protocol: UDP
    port: 31338
    targetPort: 31338
    nodePort: 31338
    name: "steam"
